# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(default='http://tarina.herokuapp.com/static/images/default.jpg'),
        ),
    ]
