# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_storyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blacklist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
