# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_blacklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyline',
            options={'ordering': ['posted_on']},
        ),
        migrations.AddField(
            model_name='story',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
