# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20170325_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='blacklist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='storyline',
            unique_together=set([('story', 'content')]),
        ),
    ]
